### ISSUE TITLE
Level05 Main.hs asks to load config in two places

### ISSUE THREAD

**Issue by AlexeyRaga** [qfpl/applied-fp-course#13]
First time in `runApp`
https://github.com/qfpl/applied-fp-course/blob/master/level05/src/FirstApp/Main.hs#L49

Second time in `prepareAppReqs`
https://github.com/qfpl/applied-fp-course/blob/master/level05/src/FirstApp/Main.hs#L58

I think that `runApp` is meant to call `prepareAppReqs` instead and should not be concerned about how `Conf` is instantiated.

**Comment by mankyKitty** [comment]
It should now be a bit more obvious that you're only supposed to load the configuration once, using the ``prepareAppReqs`` function. 👍
