### ISSUE TITLE
level02: Introduce newtype wrappers near definition of RqType?

### ISSUE THREAD

**Issue by endgame** [qfpl/applied-fp-course#24]
Currently, the way level02's `Types.hs` is laid out puts the `newtype` definitions of `Topic` and `CommentText` a fair way down the screen, and probably "below the fold". I would hoist them above the definitions of `Error` and `ContentType` so they're visible when people write the different request constructors. Otherwise people might try to build them out of raw `Text`s, and then go "oh, that's what this is for".

**Comment by mankyKitty** [comment]
Moved the `newtype` definitions to above the `RqType` defintion and it seemed to work well. Considering this fixed for now. 👍
