### ISSUE TITLE
ghcid & stack issues on NixOS

### ISSUE THREAD

**Issue by dmvianna** [qfpl/applied-fp-course#29]
Hi, Sean.

`~/.stack/config.yaml`
```yaml
system-ghc: true
nix:
  enable: true
  packages: [ glpk pcre perl gcc ncurses zlib ]
```
When I run `stack test` in level03, it compiles and runs the tests as expected. `stack test --file-watch`, though, remains silent, apparently not compiling at start neither if I change anything in the test file.

Also,
```bash
$ ghcid -c "stack repl level03-tests"
Loading stack repl level03-tests ...
Warning: File listed in level03.cabal file does not exist: ChangeLog.md
The following target packages were not found: level03-tests
See https://docs.haskellstack.org/en/v1.4.0/build_command/#target-syntax for details.

Command "stack repl level03-tests" exited unexpectedly
```
`ghcid -c "stack repl level03"` runs perfectly fine.

**Comment by endgame** [comment]
Stack's file-watch is weird on my copy of nixos too. Does the watch start if you hit return an extra time after running `stack test --file-watch`?

**Comment by dmvianna** [comment]
Positive! Yes, that's really weird. However I'm glad you found this Easter egg, that means I can use it from now on!

**Comment by endgame** [comment]
Looks like https://github.com/commercialhaskell/stack/issues/2955 ?

**Comment by mankyKitty** [comment]
Leaving this issue open for now as the stack issue is still unchanged and people may benefit from seeing they're not the only ones that have encountered this. :disappointed:

**Comment by endgame** [comment]
I haven't been having this issue lately, perhaps something has changed recently? I'm still on stack 1.6.5 but have since upgraded to the 18.03 channel
