### ISSUE TITLE
HKD Bonus stage for Config

### ISSUE THREAD

**Issue by endgame** [qfpl/applied-fp-course#84]
We define configs and partial configs, but with HKD being used more often these days maybe we want a bonus level where you define
```haskell
data Config f = Config
  { port :: f Port
  , dbPath :: f DBFilePath
  }

instance Semigroup (Config Last)
instance Monoid (Config Last)
```
?

**Comment by mankyKitty** [comment]
> Double jeopardy round where the scores can really change

Use `deriving via`

**Comment by endgame** [comment]
How? Won't we be plugging in different things in for `f`, explicitly? I'm not sure I understand.
