### ISSUE TITLE
Data.Monoid.Last will be deprecated

### ISSUE THREAD

**Issue by endgame** [qfpl/applied-fp-course#86]
https://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Monoid.html#t:Last

> This type will be marked deprecated in GHC 8.8, and removed in GHC 8.10. Users are advised to use the variant from Data.Semigroup and wrap it in Maybe.

**Comment by mankyKitty** [comment]
Should be fixed by #88 being merged.
